{
 "title": "1  Node Exporter for Prometheus Dashboard CN v20191102",
 "description": "【中文版本】支持 Node Exporter v0.16及以上的版本，精简优化重要指标展示。包含：CPU 内存 磁盘 IO 网络 温度等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP( 自动关联主机名)",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "最大分区($maxmount)使用率"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100",
     "legendFormat": "交换分区使用率"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "进程CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=\"mysqld\"} * 0.01",
     "legendFormat": "{{instance}}_mysqld"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=\"mongod\"} * 0.01",
     "legendFormat": "{{instance}}_mongod"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_1_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_2_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_3_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_4_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_5_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_6_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_7_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_8_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_9_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_10_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_11_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_12_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_13_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_14_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_cpu_percent{instance=~\"$node\",mode=~\"java_15_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "进程MEM使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=\"mysqld\"} * 0.01",
     "legendFormat": "{{instance}}_mysqld"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=\"mongod\"} * 0.01",
     "legendFormat": "{{instance}}_mongod"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_1_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_2_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_3_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_4_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_5_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_6_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_7_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_8_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_9_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_10_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_11_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_12_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_13_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_14_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    },
    {
     "expr": "process_memory_percent{instance=~\"$node\",mode=~\"java_15_.*\"} * 0.01",
     "legendFormat": "{{instance}}_{{mode}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_可用"
    }
   ]
  },
  {
   "title": "分时磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "每秒磁盘读写速度",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗费的时间",
   "type": "graph",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
   "type": "graph",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$node\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "硬件温度(虚拟机可能无法显示该项)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  }
 ]
}